id: P006884
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1854
  title: རྡོ་རྗེ་གླིང་པའི་ཟབ་གཏེར་རྣམས་དང་མཇལ་བའི་གཏེར་བྱང་རྣམ་ཐར་
  author: ''
  volumes:
    a30f7053bdb14dc59cd92ba317ea0c97:
      image_group_id: I1CZ1906
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
